import AppKit
import FappSwapCore
import os

private let logger = Logger(subsystem: "com.firatcansucu.fappswap", category: "ClipboardRecorder")

/// Watches the general pasteboard and records what the user copies.
///
/// macOS has no clipboard-change notification, so this polls `changeCount` —
/// an integer read — every 0.35 s on the main run loop and reads contents only
/// when it moves. That poll is the entire steady-state cost.
///
/// Runs on the main thread, the same thread the event tap's callback runs on,
/// so nothing here may block: text is a memory copy; image decoding,
/// thumbnailing and PNG encoding hop to `decodeQueue` and come back to the main
/// thread only to call the store.
final class ClipboardRecorder {
    private static let interval: TimeInterval = 0.35
    /// Long edge of the thumbnail in pixels.
    private static let thumbnailMaxEdge = 96
    /// Set by password managers (1Password, Bitwarden, Apple Passwords) on
    /// their writes precisely so clipboard managers skip them. Not configurable.
    private static let skippedTypes: [NSPasteboard.PasteboardType] = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ].map { NSPasteboard.PasteboardType($0) }

    /// Per-session; not persisted. Logged because a paused recorder and a
    /// broken one look the same from the outside.
    var isPaused = false {
        didSet {
            guard isPaused != oldValue else { return }
            logger.notice("recording \(self.isPaused ? "paused" : "resumed", privacy: .public)")
        }
    }
    /// Called on the main thread after every recorded item, so an open panel
    /// can refresh.
    var onChange: () -> Void = {}
    private(set) var isRunning = false

    private let store: ClipboardHistoryStore
    private let writer: PasteboardWriter
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int
    private let decodeQueue = DispatchQueue(label: "com.firatcansucu.fappswap.clipboard-decode", qos: .utility)

    init(store: ClipboardHistoryStore, writer: PasteboardWriter) {
        self.store = store
        self.writer = writer
        // Whatever is on the clipboard at launch predates the recorder and is
        // not recorded.
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: Self.interval, repeats: true) { [weak self] _ in
            self?.tick()
        }
        timer.tolerance = 0.1
        // `.common` so it keeps ticking while a menu is open.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
        isRunning = true
        logger.notice("recorder started")
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        isRunning = false
        logger.notice("recorder stopped")
    }

    private func tick() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        // Order matters: the app's own writes (expansion's borrow and restore,
        // the panel's paste) are skipped before anything else is looked at, and
        // consumed even while paused so the set can't fill with stale counts.
        if writer.consumeOwnChange(count) { return }
        if isPaused { return }
        if let reason = skippedTypeName() {
            logger.notice("skipped item marked \(reason, privacy: .public)")
            return
        }

        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        // Text wins over an image when both are present (Excel, Numbers and
        // Word put a rendering beside the text). Blank text does not count as
        // text, so an image with an empty string alongside is still recorded.
        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            recordText(text, source: source)
            return
        }
        if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) {
            // Checked before any decode/thumbnail/encode work: an oversized image
            // must be rejected on the raw bytes, not after paying for the decode.
            guard data.count <= RetentionPolicy.maxSingleImageBytes else {
                logger.notice("skipped image (\(data.count, privacy: .public) bytes): over the single-image cap")
                return
            }
            recordImage(data, source: source)
        }
    }

    /// The `org.nspasteboard.*` type name that matched a skip rule, if any — the
    /// log is the only window into which rule fired, since the item's contents
    /// are never logged.
    private func skippedTypeName() -> String? {
        for item in pasteboard.pasteboardItems ?? [] {
            if let match = item.types.first(where: { Self.skippedTypes.contains($0) }) {
                return match.rawValue
            }
        }
        return nil
    }

    private func recordText(_ text: String, source: String?) {
        do {
            if try store.recordText(text, sourceBundleID: source) != nil {
                logger.notice("recorded text (\(text.utf8.count, privacy: .public) bytes) from \(source ?? "unknown", privacy: .public)")
                onChange()
            } else {
                logger.notice("skipped text (\(text.utf8.count, privacy: .public) bytes): blank or over the cap")
            }
        } catch {
            logger.error("could not save clipboard history: \(error.localizedDescription, privacy: .public)")
        }
    }

    private func recordImage(_ data: Data, source: String?) {
        decodeQueue.async { [weak self] in
            guard let rep = NSBitmapImageRep(data: data),
                  let png = rep.representation(using: .png, properties: [:]),
                  let thumbnail = Self.thumbnailPNG(from: rep, maxEdge: Self.thumbnailMaxEdge)
            else {
                logger.notice("skipped image: could not decode \(data.count, privacy: .public) bytes")
                return
            }
            let width = rep.pixelsWide, height = rep.pixelsHigh
            DispatchQueue.main.async {
                guard let self else { return }
                do {
                    try self.store.recordImage(
                        png: png, thumbnail: thumbnail, pixelWidth: width, pixelHeight: height,
                        sourceBundleID: source)
                    logger.notice("recorded image \(width, privacy: .public)×\(height, privacy: .public) (\(png.count, privacy: .public) bytes) from \(source ?? "unknown", privacy: .public)")
                    self.onChange()
                } catch {
                    logger.error("could not save clipboard image: \(error.localizedDescription, privacy: .public)")
                }
            }
        }
    }

    /// Draws `rep` scaled so its long edge is `maxEdge` pixels, into a fresh
    /// bitmap. Runs on `decodeQueue`: `NSGraphicsContext.current` is
    /// thread-local, so drawing into an offscreen bitmap off-main is allowed.
    private static func thumbnailPNG(from rep: NSBitmapImageRep, maxEdge: Int) -> Data? {
        let w = rep.pixelsWide, h = rep.pixelsHigh
        guard w > 0, h > 0 else { return nil }
        let scale = min(1.0, Double(maxEdge) / Double(max(w, h)))
        let tw = max(1, Int((Double(w) * scale).rounded()))
        let th = max(1, Int((Double(h) * scale).rounded()))
        guard let thumb = NSBitmapImageRep(
            bitmapDataPlanes: nil, pixelsWide: tw, pixelsHigh: th, bitsPerSample: 8,
            samplesPerPixel: 4, hasAlpha: true, isPlanar: false, colorSpaceName: .deviceRGB,
            bytesPerRow: 0, bitsPerPixel: 0)
        else { return nil }
        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: thumb)
        rep.draw(in: NSRect(x: 0, y: 0, width: tw, height: th))
        NSGraphicsContext.restoreGraphicsState()
        return thumb.representation(using: .png, properties: [:])
    }
}
